version: '3.5'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - kafkanet
  kafka:
    # -----------------------------------------------------------------------------
    # For connections _internal_ to the docker network, such as from other services
    # and components, use kafka:29092.
    #
    # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
    # -----------------------------------------------------------------------------
    image: confluentinc/cp-kafka:5.2.2
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - kafkanet
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  springstream-kafka:
    build:
      context: ../
      dockerfile: ./docker/springstream-kafka.Dockerfile
    image: "softvisionlvcp/demo-spring-stream-kafka:latest"
    environment:
      KAFKA_BROKERS: kafka:29092
    ports:
      - 8080:8080
    networks:
      - kafkanet
    depends_on:
      - kafka

networks:
  kafkanet:
    name: custom_network